# specify VHDL standard to use (optional; defaults to VHDL2008)
standard = "2008"


[libraries]

UNISIM.files = [
    '/tools/Xilinx/Vivado/2021.2/data/vhdl/src/unisims/unisim_VCOMP.vhd',
]
UNISIM.is_third_party = true

UNIMACRO.files = [
    '/tools/Xilinx/Vivado/2021.2/data/vhdl/src/unimacro/unimacro_VCOMP.vhd',
]
UNIMACRO.is_third_party = true

lib1.files = [
    'rtl/*.vhd',
]
lib1.is_third_party = false

lib2.files = [
    'tb/*.vhd',
]
lib2.is_third_party = false

[lint]
# Customize linting rules as needed
unused = 'warning' # Set 'unused' diagnostics to 'warning' severity
unnecessary_work_library = false # Disable linting for the 'library work;' statement



